version: '3.8'

services:
  gateway:
    build:
      target: release
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8081:8080"

  frontend:
    build:
      target: release
    environment:
      - NODE_ENV=production
    command: npm start  # Run in production mode

  dag:
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - GUNICORN_WORKERS=4  # Number of worker processes
    command: gunicorn --workers 4 --bind 0.0.0.0:8080 'dag.web.__main__:app'  # Use gunicorn for production
