version: '3.8'

services:
  webserver:
    build:
      context: ./services/webserver
      dockerfile: Dockerfile
    container_name: webserver-service
    ports:
      - "8080:8081"
    environment:
      - GATEWAY_URL=http://gateway:8080
      - PORT=8081
    networks:
      - frontend-network

  dag:
    build:
      context: ./services/dag
      dockerfile: Dockerfile
    container_name: dag-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PYTHONPATH=/usr/src/app/src
    networks:
      - microservices-network

  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8081:8080"
    environment:
      - DagClient__BaseUrl=http://dag:8080
    networks:
      - microservices-network
      - frontend-network
    depends_on:
      - dag
      - webserver

networks:
  frontend-network:
    driver: bridge
  microservices-network:
    driver: bridge