version: '3.8'

services:
  proxy:
    build:
      context: ./services/proxy
      dockerfile: Dockerfile
    container_name: proxy-service
    ports:
      - "80:80"
    networks:
      - gateway-bridge
      - frontend-bridge
    depends_on:
      - frontend
      - gateway

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    ports:
      - "8080:3000"
    networks:
      - frontend-bridge

  dag:
    build:
      context: ./services/dag
      dockerfile: Dockerfile
    container_name: dag-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PYTHONPATH=/usr/src/app/src
    networks:
      - microservices-network

  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8081:8080"
    environment:
      - DagClient__BaseUrl=http://dag:8080
    networks:
      - gateway-bridge
      - microservices-network
    depends_on:
      - dag
      - frontend

networks:
  frontend-bridge:
    driver: bridge
  gateway-bridge:
    driver: bridge
  microservices-network:
    driver: bridge