version: '3.8'

services:
  webserver-service:
    build:
      context: ./services/webserver
      dockerfile: Dockerfile
    container_name: webserver-service
    ports:
      - "8080:8081"
    networks:
      - microservices-network

  dag-service:
    build:
      context: ./services/dag
      dockerfile: Dockerfile
    container_name: dag-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PYTHONPATH=/usr/src/app/src
    networks:
      - microservices-network

  gateway-service:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8081:8080"
    networks:
      - microservices-network
    depends_on:
      - dag-service
      - webserver-service

networks:
  microservices-network:
    driver: bridge